In [1]:
import seaborn as sns

import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd

# 메모장 파일 불러오기
with open('wine.data.txt', 'r', encoding='utf-8') as file:
    data = file.readlines()

# 데이터를 파싱하여 DataFrame 만들기
data_list = []
for line in data:
    columns = line.strip().split(',')  # 쉼표로 열을 분할하고 양쪽 공백 제거
    data_list.append(columns)

# 열 이름 지정
column_names = ["Label", "Alcohol", "Malic acid", "Ash", "Alcalinity of ash", "Magnesium",
           "Total phenols", "Flavanoids", "Nonflavanoid phenols", "Proanthocyanins",
           "Color intensity", "Hue", "OD280/OD315 of diluted wines", "Proline"]  # 실제 열 이름으로 바꿔주세요

# DataFrame 생성 및 열 이름 설정
df = pd.DataFrame(data_list, columns=column_names)

# DataFrame 출력
print(df)


    Label Alcohol Malic acid   Ash Alcalinity of ash Magnesium Total phenols  \
0       1   14.23       1.71  2.43              15.6       127           2.8   
1       1    13.2       1.78  2.14              11.2       100          2.65   
2       1   13.16       2.36  2.67              18.6       101           2.8   
3       1   14.37       1.95   2.5              16.8       113          3.85   
4       1   13.24       2.59  2.87                21       118           2.8   
..    ...     ...        ...   ...               ...       ...           ...   
173     3   13.71       5.65  2.45              20.5        95          1.68   
174     3    13.4       3.91  2.48                23       102           1.8   
175     3   13.27       4.28  2.26                20       120          1.59   
176     3   13.17       2.59  2.37                20       120          1.65   
177     3   14.13        4.1  2.74              24.5        96          2.05   

    Flavanoids Nonflavanoid phenols Pro

In [4]:
x = df
x = x.drop(columns=['Label'], axis=1)

In [5]:
y = df['Label']

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Label, Length: 178, dtype: object

In [10]:
df.isna().sum()

Label                           0
Alcohol                         0
Malic acid                      0
Ash                             0
Alcalinity of ash               0
Magnesium                       0
Total phenols                   0
Flavanoids                      0
Nonflavanoid phenols            0
Proanthocyanins                 0
Color intensity                 0
Hue                             0
OD280/OD315 of diluted wines    0
Proline                         0
dtype: int64

In [11]:
# train & test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((133, 13), (45, 13), (133,), (45,))

In [12]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.8222222222222222
[[15  0  1]
 [ 0 17  4]
 [ 0  3  5]]


In [13]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


In [14]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


In [15]:
# RT

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]
