In [1]:
import seaborn as sns

import numpy as np

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

# 메모장 파일 불러오기
with open('car.data', 'r', encoding='utf-8') as file:
    data = file.readlines()

# 데이터를 파싱하여 DataFrame 만들기
data_list = []
for line in data:
    columns = line.strip().split(',')  # 쉼표로 열을 분할하고 양쪽 공백 제거
    data_list.append(columns)

# 열 이름 지정
column_names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "Label"]  # 실제 열 이름으로 바꿔주세요

# DataFrame 생성 및 열 이름 설정
df = pd.DataFrame(data_list, columns=column_names)

# DataFrame 출력
# print(df)
df.head()

buying  maint doors persons lug_boot safety  Label
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [3]:
df.keys()

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'Label'], dtype='object')

In [4]:
print(df["Label"])

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: Label, Length: 1728, dtype: object


In [19]:
# 클래스의 내용들을 숫자로 바꿔줌
# buying
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['buying_f']=label.fit_transform(df['buying'])

# maint 
df['maint_f']=label.fit_transform(df['maint'])

# doors
df['doors_f']=label.fit_transform(df['doors'])

# persons 
df['persons_f']=label.fit_transform(df['persons'])

# lug_boot
df['lug_boot_f']=label.fit_transform(df['lug_boot'])

# safety
df['safety_f']=label.fit_transform(df['safety'])

# Label
df["Label_f"]=label.fit_transform(df["Label"])
print(df)

df.head()

     buying  maint  doors persons lug_boot safety  Label  buying_f  maint_f  \
0     vhigh  vhigh      2       2    small    low  unacc         3        3   
1     vhigh  vhigh      2       2    small    med  unacc         3        3   
2     vhigh  vhigh      2       2    small   high  unacc         3        3   
3     vhigh  vhigh      2       2      med    low  unacc         3        3   
4     vhigh  vhigh      2       2      med    med  unacc         3        3   
...     ...    ...    ...     ...      ...    ...    ...       ...      ...   
1723    low    low  5more    more      med    med   good         1        1   
1724    low    low  5more    more      med   high  vgood         1        1   
1725    low    low  5more    more      big    low  unacc         1        1   
1726    low    low  5more    more      big    med   good         1        1   
1727    low    low  5more    more      big   high  vgood         1        1   

      doors_f  persons_f  lug_boot_f  safety_f  Lab

buying  maint doors persons lug_boot safety  Label  buying_f  maint_f  \
0  vhigh  vhigh     2       2    small    low  unacc         3        3   
1  vhigh  vhigh     2       2    small    med  unacc         3        3   
2  vhigh  vhigh     2       2    small   high  unacc         3        3   
3  vhigh  vhigh     2       2      med    low  unacc         3        3   
4  vhigh  vhigh     2       2      med    med  unacc         3        3   

   doors_f  persons_f  lug_boot_f  safety_f  Label_f  
0        0          0           2         1        2  
1        0          0           2         2        2  
2        0          0           2         0        2  
3        0          0           1         1        2  
4        0          0           1         2        2

In [23]:
# 숫자로 바꿨으니, 문자열이었던 것들 drop
x = df
x = x.drop(columns=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'Label', 'Label_f'], axis=1)

In [24]:
y = df['Label_f']

In [25]:
x

buying_f  maint_f  doors_f  persons_f  lug_boot_f  safety_f
0            3        3        0          0           2         1
1            3        3        0          0           2         2
2            3        3        0          0           2         0
3            3        3        0          0           1         1
4            3        3        0          0           1         2
...        ...      ...      ...        ...         ...       ...
1723         1        1        3          2           1         2
1724         1        1        3          2           1         0
1725         1        1        3          2           0         1
1726         1        1        3          2           0         2
1727         1        1        3          2           0         0

[1728 rows x 6 columns]

In [27]:
# 결측치 제거
df.isna().sum()

buying        0
maint         0
doors         0
persons       0
lug_boot      0
safety        0
Label         0
buying_f      0
maint_f       0
doors_f       0
persons_f     0
lug_boot_f    0
safety_f      0
Label_f       0
dtype: int64

In [29]:
# train & test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1296, 6), (432, 6), (1296,), (432,))

In [30]:
# SVM

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.9212962962962963
[[ 82   1  15   1]
 [  7  11   0   3]
 [  2   0 294   0]
 [  5   0   0  11]]


In [31]:
# DT

from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9768518518518519
[[ 92   4   3   0]
 [  0  21   0   0]
 [  2   0 294   0]
 [  1   0   0  15]]


In [32]:
# RF

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Random Forest ---
0.9745370370370371
[[ 95   3   1   0]
 [  2  19   0   0]
 [  3   0 293   0]
 [  2   0   0  14]]


In [33]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.6550925925925926
[[ 11   0  84   4]
 [  1   0  20   0]
 [ 24   0 269   3]
 [  4   0   9   3]]
